export const TABLE_HEADERS = [
  { header: 'id', width: 60 },
  { header: 'title', sort: true, width: 300 },
  { header: 'language', width: 200 },
  { header: 'content type', width: 200 },
  { header: 'version', width: 100 },
  { header: 'publish status', width: 150 },
  { header: 'variant info', width: 150 },
  { header: 'modified at', width: 150 },
  { header: 'tags', width: 150 },
  { header: 'taxonomies', width: 150 },
  { header: 'actions', width: 150 },
];

export const TABLE_DATA = [
  {
    id: 868,
    title: 'That Wonderful Tale',
    language: 'English',
    'content type': 'Vlog',
    version: 4,
    'publish status': 'Archived',
    'variant info': 'Variant Q',
    'modified at': '2024-04-27',
    tags: ['tag5', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 219,
    title: 'Your Unbelievable Tale',
    language: 'Spanish',
    'content type': 'Text',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant Z',
    'modified at': '2024-04-12',
    tags: ['tag2', 'tag3'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 714,
    title: 'Our Wonderful Journey',
    language: 'Russian',
    'content type': 'Vlog',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant A',
    'modified at': '2024-02-22',
    tags: ['tag4', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 369,
    title: 'The Incredible Voyage',
    language: 'German',
    'content type': 'Text',
    version: 4,
    'publish status': 'Archived',
    'variant info': 'Variant I',
    'modified at': '2024-03-04',
    tags: ['tag4', 'tag4'],
    taxonomies: ['taxonomy3', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 155,
    title: 'Some Fantastic Voyage',
    language: 'Italian',
    'content type': 'Blog',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant H',
    'modified at': '2024-05-16',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy5', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 942,
    title: 'Some Unbelievable Quest',
    language: 'French',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant M',
    'modified at': '2024-03-23',
    tags: ['tag5', 'tag2'],
    taxonomies: ['taxonomy5', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 907,
    title: 'Any Awesome Experience',
    language: 'Portuguese',
    'content type': 'Blog',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant Q',
    'modified at': '2024-05-01',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 710,
    title: 'Your Awesome Quest',
    language: 'Arabic',
    'content type': 'Image',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant K',
    'modified at': '2024-05-13',
    tags: ['tag1', 'tag5'],
    taxonomies: ['taxonomy5', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 724,
    title: 'This Unbelievable Tale',
    language: 'Russian',
    'content type': 'Text',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant W',
    'modified at': '2024-03-14',
    tags: ['tag1', 'tag1'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 139,
    title: 'This Phenomenal Experience',
    language: 'Portuguese',
    'content type': 'Text',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant T',
    'modified at': '2024-03-16',
    tags: ['tag1', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 127,
    title: 'Any Awesome Excursion',
    language: 'Arabic',
    'content type': 'Blog',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant M',
    'modified at': '2024-04-06',
    tags: ['tag1', 'tag1'],
    taxonomies: ['taxonomy2', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 303,
    title: 'Our Wonderful Experience',
    language: 'German',
    'content type': 'Image',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant C',
    'modified at': '2024-03-07',
    tags: ['tag3', 'tag4'],
    taxonomies: ['taxonomy4', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 103,
    title: 'Every Unbelievable Voyage',
    language: 'Arabic',
    'content type': 'Text',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant V',
    'modified at': '2024-02-21',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 211,
    title: 'Any Awesome Narrative',
    language: 'English',
    'content type': 'News',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant B',
    'modified at': '2024-03-31',
    tags: ['tag4', 'tag2'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 605,
    title: 'This Phenomenal Voyage',
    language: 'Portuguese',
    'content type': 'Text',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant U',
    'modified at': '2024-04-23',
    tags: ['tag3', 'tag1'],
    taxonomies: ['taxonomy4', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 526,
    title: 'Every Extraordinary Expedition',
    language: 'Portuguese',
    'content type': 'Video',
    version: 3,
    'publish status': 'Archived',
    'variant info': 'Variant T',
    'modified at': '2024-03-19',
    tags: ['tag5', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 347,
    title: 'Any Remarkable Expedition',
    language: 'Arabic',
    'content type': 'Video',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant A',
    'modified at': '2024-03-16',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 903,
    title: 'My Phenomenal Tale',
    language: 'Italian',
    'content type': 'Video',
    version: 4,
    'publish status': 'Published',
    'variant info': 'Variant K',
    'modified at': '2024-04-09',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy5', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 418,
    title: 'My Incredible Voyage',
    language: 'Chinese',
    'content type': 'Text',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant H',
    'modified at': '2024-03-02',
    tags: ['tag2', 'tag5'],
    taxonomies: ['taxonomy3', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 335,
    title: 'Some Awesome Quest',
    language: 'Japanese',
    'content type': 'Text',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant Y',
    'modified at': '2024-03-24',
    tags: ['tag3', 'tag4'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 181,
    title: 'Some Extraordinary Adventure',
    language: 'Portuguese',
    'content type': 'Vlog',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant B',
    'modified at': '2024-04-06',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 749,
    title: 'Our Amazing Experience',
    language: 'English',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant B',
    'modified at': '2024-03-21',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy3', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 765,
    title: 'That Extraordinary Voyage',
    language: 'Spanish',
    'content type': 'Text',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant L',
    'modified at': '2024-03-12',
    tags: ['tag1', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 193,
    title: 'Every Awesome Quest',
    language: 'Italian',
    'content type': 'Video',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant F',
    'modified at': '2024-05-15',
    tags: ['tag5', 'tag2'],
    taxonomies: ['taxonomy5', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 377,
    title: 'Your Extraordinary Quest',
    language: 'German',
    'content type': 'News',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant E',
    'modified at': '2024-03-30',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 133,
    title: 'Your Fantastic Experience',
    language: 'French',
    'content type': 'Image',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant X',
    'modified at': '2024-04-15',
    tags: ['tag4', 'tag1'],
    taxonomies: ['taxonomy2', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 594,
    title: 'Our Phenomenal Excursion',
    language: 'Arabic',
    'content type': 'Blog',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant D',
    'modified at': '2024-02-11',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 637,
    title: 'Some Unbelievable Voyage',
    language: 'Arabic',
    'content type': 'Video',
    version: 4,
    'publish status': 'Archived',
    'variant info': 'Variant M',
    'modified at': '2024-02-24',
    tags: ['tag3', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 161,
    title: 'This Fantastic Experience',
    language: 'Portuguese',
    'content type': 'Vlog',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant M',
    'modified at': '2024-02-28',
    tags: ['tag1', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 275,
    title: 'Your Remarkable Adventure',
    language: 'English',
    'content type': 'News',
    version: 5,
    'publish status': 'Draft',
    'variant info': 'Variant N',
    'modified at': '2024-03-21',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 20,
    title: 'Some Awesome Adventure',
    language: 'German',
    'content type': 'News',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant J',
    'modified at': '2024-05-17',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy2', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 235,
    title: 'Any Awesome Voyage',
    language: 'English',
    'content type': 'Podcast',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant I',
    'modified at': '2024-04-20',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 477,
    title: 'Our Awesome Story',
    language: 'Italian',
    'content type': 'Vlog',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant M',
    'modified at': '2024-02-14',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy3', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 675,
    title: 'Every Remarkable Quest',
    language: 'Italian',
    'content type': 'Blog',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant Q',
    'modified at': '2024-03-04',
    tags: ['tag4', 'tag4'],
    taxonomies: ['taxonomy1', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 173,
    title: 'Every Unbelievable Excursion',
    language: 'Arabic',
    'content type': 'Image',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant S',
    'modified at': '2024-03-27',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 800,
    title: 'The Awesome Excursion',
    language: 'Italian',
    'content type': 'Video',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant E',
    'modified at': '2024-05-16',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 172,
    title: 'This Unbelievable Excursion',
    language: 'Japanese',
    'content type': 'Image',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant R',
    'modified at': '2024-03-20',
    tags: ['tag2', 'tag1'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 662,
    title: 'Every Incredible Expedition',
    language: 'Italian',
    'content type': 'Video',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant U',
    'modified at': '2024-05-18',
    tags: ['tag2', 'tag4'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 401,
    title: 'This Astonishing Tale',
    language: 'German',
    'content type': 'Podcast',
    version: 5,
    'publish status': 'Draft',
    'variant info': 'Variant P',
    'modified at': '2024-02-23',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy4', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 170,
    title: 'That Amazing Narrative',
    language: 'German',
    'content type': 'Blog',
    version: 4,
    'publish status': 'Archived',
    'variant info': 'Variant B',
    'modified at': '2024-02-25',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 680,
    title: 'Every Amazing Journey',
    language: 'Chinese',
    'content type': 'Video',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant H',
    'modified at': '2024-04-09',
    tags: ['tag5', 'tag5'],
    taxonomies: ['taxonomy2', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 359,
    title: 'Every Extraordinary Adventure',
    language: 'Chinese',
    'content type': 'Podcast',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant G',
    'modified at': '2024-04-13',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 139,
    title: 'Our Amazing Journey',
    language: 'English',
    'content type': 'Blog',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant Z',
    'modified at': '2024-04-28',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy5', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 572,
    title: 'This Awesome Narrative',
    language: 'Chinese',
    'content type': 'Image',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant S',
    'modified at': '2024-05-15',
    tags: ['tag1', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 861,
    title: 'Every Phenomenal Adventure',
    language: 'Japanese',
    'content type': 'Vlog',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant V',
    'modified at': '2024-04-19',
    tags: ['tag3', 'tag3'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 560,
    title: 'This Wonderful Adventure',
    language: 'Japanese',
    'content type': 'Video',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant O',
    'modified at': '2024-02-23',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 546,
    title: 'That Wonderful Expedition',
    language: 'Spanish',
    'content type': 'Vlog',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant Q',
    'modified at': '2024-02-18',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy5', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 857,
    title: 'Some Wonderful Adventure',
    language: 'Russian',
    'content type': 'News',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant E',
    'modified at': '2024-04-13',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 324,
    title: 'This Fantastic Tale',
    language: 'Spanish',
    'content type': 'Text',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant U',
    'modified at': '2024-05-17',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 989,
    title: 'Any Remarkable Narrative',
    language: 'Chinese',
    'content type': 'Text',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant L',
    'modified at': '2024-03-15',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 517,
    title: 'Some Wonderful Experience',
    language: 'Spanish',
    'content type': 'News',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant U',
    'modified at': '2024-03-12',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy3', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 675,
    title: 'The Extraordinary Expedition',
    language: 'Italian',
    'content type': 'Text',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant J',
    'modified at': '2024-05-03',
    tags: ['tag1', 'tag1'],
    taxonomies: ['taxonomy2', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 339,
    title: 'That Unbelievable Experience',
    language: 'French',
    'content type': 'Blog',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant F',
    'modified at': '2024-05-19',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy4', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 844,
    title: 'Our Awesome Excursion',
    language: 'French',
    'content type': 'Image',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant N',
    'modified at': '2024-03-20',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 68,
    title: 'Every Astonishing Adventure',
    language: 'Portuguese',
    'content type': 'Blog',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant B',
    'modified at': '2024-05-01',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy4', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 439,
    title: 'The Awesome Narrative',
    language: 'French',
    'content type': 'Text',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant L',
    'modified at': '2024-04-25',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 917,
    title: 'Your Phenomenal Excursion',
    language: 'German',
    'content type': 'Video',
    version: 5,
    'publish status': 'Draft',
    'variant info': 'Variant H',
    'modified at': '2024-03-27',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy3', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 552,
    title: 'Your Phenomenal Adventure',
    language: 'French',
    'content type': 'Image',
    version: 4,
    'publish status': 'Archived',
    'variant info': 'Variant V',
    'modified at': '2024-03-02',
    tags: ['tag2', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 391,
    title: 'This Extraordinary Narrative',
    language: 'Spanish',
    'content type': 'Vlog',
    version: 4,
    'publish status': 'Published',
    'variant info': 'Variant U',
    'modified at': '2024-02-16',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy2', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 449,
    title: 'Our Phenomenal Quest',
    language: 'Spanish',
    'content type': 'Podcast',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant G',
    'modified at': '2024-04-16',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy3', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 205,
    title: 'Your Astonishing Experience',
    language: 'English',
    'content type': 'News',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant X',
    'modified at': '2024-04-11',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 871,
    title: 'Any Unbelievable Tale',
    language: 'Japanese',
    'content type': 'Image',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant O',
    'modified at': '2024-05-07',
    tags: ['tag5', 'tag4'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 928,
    title: 'Our Awesome Excursion',
    language: 'German',
    'content type': 'Video',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant Q',
    'modified at': '2024-04-08',
    tags: ['tag3', 'tag4'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 451,
    title: 'All Astonishing Experience',
    language: 'Arabic',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant K',
    'modified at': '2024-02-21',
    tags: ['tag3', 'tag1'],
    taxonomies: ['taxonomy2', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 799,
    title: 'Our Awesome Voyage',
    language: 'Spanish',
    'content type': 'Blog',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant O',
    'modified at': '2024-03-17',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 450,
    title: 'Any Extraordinary Journey',
    language: 'German',
    'content type': 'Image',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant H',
    'modified at': '2024-03-09',
    tags: ['tag1', 'tag3'],
    taxonomies: ['taxonomy2', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 966,
    title: 'Some Incredible Voyage',
    language: 'Chinese',
    'content type': 'Podcast',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant H',
    'modified at': '2024-04-18',
    tags: ['tag3', 'tag2'],
    taxonomies: ['taxonomy1', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 465,
    title: 'This Remarkable Narrative',
    language: 'Italian',
    'content type': 'Text',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant B',
    'modified at': '2024-03-06',
    tags: ['tag4', 'tag2'],
    taxonomies: ['taxonomy4', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 745,
    title: 'Some Phenomenal Experience',
    language: 'Chinese',
    'content type': 'Text',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant Q',
    'modified at': '2024-04-15',
    tags: ['tag3', 'tag3'],
    taxonomies: ['taxonomy2', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 484,
    title: 'Our Fantastic Expedition',
    language: 'Spanish',
    'content type': 'Image',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant V',
    'modified at': '2024-05-18',
    tags: ['tag2', 'tag5'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 576,
    title: 'Our Amazing Tale',
    language: 'Spanish',
    'content type': 'Blog',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant T',
    'modified at': '2024-03-06',
    tags: ['tag1', 'tag4'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 513,
    title: 'Every Wonderful Journey',
    language: 'Russian',
    'content type': 'Text',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant W',
    'modified at': '2024-04-20',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 195,
    title: 'Every Remarkable Excursion',
    language: 'German',
    'content type': 'Text',
    version: 2,
    'publish status': 'Archived',
    'variant info': 'Variant N',
    'modified at': '2024-03-03',
    tags: ['tag2', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 709,
    title: 'Any Remarkable Tale',
    language: 'German',
    'content type': 'News',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant Z',
    'modified at': '2024-05-17',
    tags: ['tag4', 'tag4'],
    taxonomies: ['taxonomy2', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 449,
    title: 'That Awesome Tale',
    language: 'Arabic',
    'content type': 'Vlog',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant J',
    'modified at': '2024-05-07',
    tags: ['tag3', 'tag1'],
    taxonomies: ['taxonomy4', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 218,
    title: 'This Unbelievable Tale',
    language: 'German',
    'content type': 'Video',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant T',
    'modified at': '2024-02-16',
    tags: ['tag3', 'tag4'],
    taxonomies: ['taxonomy5', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 498,
    title: 'All Extraordinary Expedition',
    language: 'Spanish',
    'content type': 'Text',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant M',
    'modified at': '2024-05-20',
    tags: ['tag1', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 139,
    title: 'Any Phenomenal Quest',
    language: 'Arabic',
    'content type': 'Image',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant I',
    'modified at': '2024-04-26',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 227,
    title: 'Your Incredible Excursion',
    language: 'French',
    'content type': 'Text',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant X',
    'modified at': '2024-02-13',
    tags: ['tag4', 'tag3'],
    taxonomies: ['taxonomy3', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 778,
    title: 'That Awesome Voyage',
    language: 'Italian',
    'content type': 'Vlog',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant H',
    'modified at': '2024-03-25',
    tags: ['tag1', 'tag1'],
    taxonomies: ['taxonomy3', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 291,
    title: 'Any Amazing Journey',
    language: 'English',
    'content type': 'Image',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant H',
    'modified at': '2024-02-21',
    tags: ['tag2', 'tag3'],
    taxonomies: ['taxonomy3', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 525,
    title: 'That Extraordinary Quest',
    language: 'Spanish',
    'content type': 'Vlog',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant C',
    'modified at': '2024-04-27',
    tags: ['tag2', 'tag4'],
    taxonomies: ['taxonomy2', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 161,
    title: 'Some Remarkable Narrative',
    language: 'Portuguese',
    'content type': 'Podcast',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant O',
    'modified at': '2024-03-01',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 24,
    title: 'Some Astonishing Adventure',
    language: 'French',
    'content type': 'Podcast',
    version: 1,
    'publish status': 'Archived',
    'variant info': 'Variant V',
    'modified at': '2024-04-11',
    tags: ['tag3', 'tag5'],
    taxonomies: ['taxonomy4', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 73,
    title: 'Our Awesome Expedition',
    language: 'Portuguese',
    'content type': 'Vlog',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant W',
    'modified at': '2024-05-04',
    tags: ['tag5', 'tag5'],
    taxonomies: ['taxonomy3', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 236,
    title: 'Our Amazing Journey',
    language: 'French',
    'content type': 'Vlog',
    version: 3,
    'publish status': 'Archived',
    'variant info': 'Variant H',
    'modified at': '2024-04-27',
    tags: ['tag5', 'tag1'],
    taxonomies: ['taxonomy3', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 216,
    title: 'Our Incredible Voyage',
    language: 'Russian',
    'content type': 'News',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant N',
    'modified at': '2024-02-24',
    tags: ['tag5', 'tag2'],
    taxonomies: ['taxonomy4', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 575,
    title: 'Your Incredible Expedition',
    language: 'Italian',
    'content type': 'Image',
    version: 4,
    'publish status': 'Published',
    'variant info': 'Variant O',
    'modified at': '2024-03-10',
    tags: ['tag2', 'tag5'],
    taxonomies: ['taxonomy5', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 903,
    title: 'Every Phenomenal Quest',
    language: 'Japanese',
    'content type': 'Text',
    version: 4,
    'publish status': 'Published',
    'variant info': 'Variant R',
    'modified at': '2024-03-03',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 405,
    title: 'The Astonishing Expedition',
    language: 'German',
    'content type': 'Podcast',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant F',
    'modified at': '2024-03-26',
    tags: ['tag4', 'tag1'],
    taxonomies: ['taxonomy5', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 413,
    title: 'Every Remarkable Narrative',
    language: 'French',
    'content type': 'Blog',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant J',
    'modified at': '2024-04-25',
    tags: ['tag3', 'tag3'],
    taxonomies: ['taxonomy5', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 764,
    title: 'Some Awesome Journey',
    language: 'Portuguese',
    'content type': 'Video',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant C',
    'modified at': '2024-02-25',
    tags: ['tag1', 'tag3'],
    taxonomies: ['taxonomy4', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
  {
    id: 432,
    title: 'This Wonderful Adventure',
    language: 'French',
    'content type': 'Podcast',
    version: 5,
    'publish status': 'Draft',
    'variant info': 'Variant X',
    'modified at': '2024-02-28',
    tags: ['tag4', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 700,
    title: 'Our Extraordinary Expedition',
    language: 'Spanish',
    'content type': 'Text',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant P',
    'modified at': '2024-02-29',
    tags: ['tag5', 'tag3'],
    taxonomies: ['taxonomy1', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 151,
    title: 'That Unbelievable Story',
    language: 'Portuguese',
    'content type': 'Podcast',
    version: 5,
    'publish status': 'Published',
    'variant info': 'Variant T',
    'modified at': '2024-04-10',
    tags: ['tag3', 'tag1'],
    taxonomies: ['taxonomy1', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 768,
    title: 'All Phenomenal Quest',
    language: 'Chinese',
    'content type': 'Text',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant Z',
    'modified at': '2024-03-31',
    tags: ['tag5', 'tag5'],
    taxonomies: ['taxonomy2', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 753,
    title: 'The Astonishing Excursion',
    language: 'Portuguese',
    'content type': 'Vlog',
    version: 5,
    'publish status': 'Archived',
    'variant info': 'Variant G',
    'modified at': '2024-02-25',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy3', 'taxonomy2'],
    actions: 'Edit/Delete',
  },
  {
    id: 62,
    title: 'This Awesome Tale',
    language: 'Arabic',
    'content type': 'Podcast',
    version: 4,
    'publish status': 'Draft',
    'variant info': 'Variant G',
    'modified at': '2024-04-15',
    tags: ['tag4', 'tag5'],
    taxonomies: ['taxonomy4', 'taxonomy3'],
    actions: 'Edit/Delete',
  },
  {
    id: 475,
    title: 'This Wonderful Tale',
    language: 'French',
    'content type': 'Blog',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant P',
    'modified at': '2024-03-20',
    tags: ['tag3', 'tag5'],
    taxonomies: ['taxonomy1', 'taxonomy1'],
    actions: 'Edit/Delete',
  },
  {
    id: 37,
    title: 'Some Unbelievable Story',
    language: 'French',
    'content type': 'Image',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant G',
    'modified at': '2024-05-06',
    tags: ['tag2', 'tag2'],
    taxonomies: ['taxonomy2', 'taxonomy5'],
    actions: 'Edit/Delete',
  },
];
