export const TABLE_HEADERS = [
  { header: 'id' },
  { header: 'title', sort: true },
  { header: 'language' },
  { header: 'content type' },
  { header: 'version' },
  { header: 'publish status' },
  { header: 'variant info' },
  { header: 'modified at' },
  { header: 'tags' },
  { header: 'taxonomies' },
  { header: 'actions' },
];

export const TABLE_DATA = [
  {
    id: 2,
    title: 'A',
    language: 'Spanish',
    'content type': 'Video',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant B',
    'modified at': '2024-05-15',
    tags: ['tag3', 'tag4'],
    taxonomies: ['taxonomy3', 'taxonomy4'],
    actions: 'Edit/Delete',
  },
  {
    id: 3,
    title: 'B',
    language: 'French',
    'content type': 'Article',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant C',
    'modified at': '2024-05-16',
    tags: ['tag5', 'tag6'],
    taxonomies: ['taxonomy5', 'taxonomy6'],
    actions: 'Edit/Delete',
  },
  {
    id: 4,
    title: 'C',
    language: 'German',
    'content type': 'Article',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant D',
    'modified at': '2024-05-17',
    tags: ['tag7', 'tag8'],
    taxonomies: ['taxonomy7', 'taxonomy8'],
    actions: 'Edit/Delete',
  },
  {
    id: 5,
    title: 'D',
    language: 'Japanese',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant E',
    'modified at': '2024-05-18',
    tags: ['tag9', 'tag10'],
    taxonomies: ['taxonomy9', 'taxonomy10'],
    actions: 'Edit/Delete',
  },
  {
    id: 6,
    title: 'E',
    language: 'Chinese',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant F',
    'modified at': '2024-05-19',
    tags: ['tag11', 'tag12'],
    taxonomies: ['taxonomy11', 'taxonomy12'],
    actions: 'Edit/Delete',
  },
  {
    id: 7,
    title: 'F',
    language: 'Italian',
    'content type': 'Article',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant G',
    'modified at': '2024-05-20',
    tags: ['tag13', 'tag14'],
    taxonomies: ['taxonomy13', 'taxonomy14'],
    actions: 'Edit/Delete',
  },
  {
    id: 8,
    title: 'G',
    language: 'Portuguese',
    'content type': 'Video',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant H',
    'modified at': '2024-05-21',
    tags: ['tag15', 'tag16'],
    taxonomies: ['taxonomy15', 'taxonomy16'],
    actions: 'Edit/Delete',
  },
  {
    id: 9,
    title: 'H',
    language: 'Russian',
    'content type': 'Article',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant I',
    'modified at': '2024-05-22',
    tags: ['tag17', 'tag18'],
    taxonomies: ['taxonomy17', 'taxonomy18'],
    actions: 'Edit/Delete',
  },
  {
    id: 10,
    title: 'I',
    language: 'Korean',
    'content type': 'Article',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant J',
    'modified at': '2024-05-23',
    tags: ['tag19', 'tag20'],
    taxonomies: [
      'taxonomy19',
      'taxonomy20',
      'taxonomy20',
      'taxonomy20',
      'taxonomy20',
      'taxonomy20',
      'taxonomy20',
    ],
    actions: 'Edit/Delete',
  },
  {
    id: 11,
    title: 'J',
    language: 'English',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant K',
    'modified at': '2024-05-24',
    tags: ['tag21', 'tag22'],
    taxonomies: ['taxonomy21', 'taxonomy22'],
    actions: 'Edit/Delete',
  },
  {
    id: 12,
    title: 'K',
    language: 'Chinese',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant L',
    'modified at': '2024-05-25',
    tags: ['tag23', 'tag24'],
    taxonomies: ['taxonomy23', 'taxonomy24'],
    actions: 'Edit/Delete',
  },
  {
    id: 13,
    title: 'L',
    language: 'Japanese',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant M',
    'modified at': '2024-05-26',
    tags: ['tag25', 'tag26'],
    taxonomies: ['taxonomy25', 'taxonomy26'],
    actions: 'Edit/Delete',
  },
  {
    id: 14,
    title: 'M',
    language: 'French',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant N',
    'modified at': '2024-05-27',
    tags: ['tag27', 'tag28'],
    taxonomies: ['taxonomy27', 'taxonomy28'],
    actions: 'Edit/Delete',
  },
  {
    id: 15,
    title: 'N',
    language: 'German',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant O',
    'modified at': '2024-05-28',
    tags: ['tag29', 'tag30'],
    taxonomies: ['taxonomy29', 'taxonomy30'],
    actions: 'Edit/Delete',
  },
  {
    id: 16,
    title: 'O',
    language: 'Portuguese',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant P',
    'modified at': '2024-05-29',
    tags: ['tag31', 'tag32'],
    taxonomies: ['taxonomy31', 'taxonomy32'],
    actions: 'Edit/Delete',
  },
  {
    id: 17,
    title: 'P',
    language: 'Italian',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant Q',
    'modified at': '2024-05-30',
    tags: ['tag33', 'tag34'],
    taxonomies: ['taxonomy33', 'taxonomy34'],
    actions: 'Edit/Delete',
  },
  {
    id: 18,
    title: 'Q',
    language: 'Spanish',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant R',
    'modified at': '2024-05-31',
    tags: ['tag35', 'tag36'],
    taxonomies: ['taxonomy35', 'taxonomy36'],
    actions: 'Edit/Delete',
  },
  {
    id: 19,
    title: 'R',
    language: 'French',
    'content type': 'Video',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant S',
    'modified at': '2024-06-01',
    tags: ['tag37', 'tag38'],
    taxonomies: ['taxonomy37', 'taxonomy38'],
    actions: 'Edit/Delete',
  },
  {
    id: 20,
    title: 'S',
    language: 'German',
    'content type': 'Article',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant T',
    'modified at': '2024-06-02',
    tags: ['tag39', 'tag40'],
    taxonomies: ['taxonomy39', 'taxonomy40'],
    actions: 'Edit/Delete',
  },
  {
    id: 21,
    title: 'T',
    language: 'Italian',
    'content type': 'Video',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant U',
    'modified at': '2024-06-03',
    tags: ['tag41', 'tag42'],
    taxonomies: ['taxonomy41', 'taxonomy42'],
    actions: 'Edit/Delete',
  },
  {
    id: 22,
    title: 'U',
    language: 'Portuguese',
    'content type': 'Article',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant V',
    'modified at': '2024-06-04',
    tags: ['tag43', 'tag44'],
    taxonomies: ['taxonomy43', 'taxonomy44'],
    actions: 'Edit/Delete',
  },
  {
    id: 23,
    title: 'V',
    language: 'Russian',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant W',
    'modified at': '2024-06-05',
    tags: ['tag45', 'tag46'],
    taxonomies: ['taxonomy45', 'taxonomy46'],
    actions: 'Edit/Delete',
  },
  {
    id: 24,
    title: 'W',
    language: 'Chinese',
    'content type': 'Article',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant X',
    'modified at': '2024-06-06',
    tags: ['tag47', 'tag48'],
    taxonomies: ['taxonomy47', 'taxonomy48'],
    actions: 'Edit/Delete',
  },
  {
    id: 25,
    title: 'X',
    language: 'Spanish',
    'content type': 'Video',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant Y',
    'modified at': '2024-06-07',
    tags: ['tag49', 'tag50'],
    taxonomies: ['taxonomy49', 'taxonomy50'],
    actions: 'Edit/Delete',
  },
  {
    id: 26,
    title: 'Y',
    language: 'French',
    'content type': 'Article',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant Z',
    'modified at': '2024-06-08',
    tags: ['tag51', 'tag52'],
    taxonomies: ['taxonomy51', 'taxonomy52'],
    actions: 'Edit/Delete',
  },
  {
    id: 27,
    title: 'Z',
    language: 'German',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant AA',
    'modified at': '2024-06-09',
    tags: ['tag53', 'tag54'],
    taxonomies: ['taxonomy53', 'taxonomy54'],
    actions: 'Edit/Delete',
  },
  {
    id: 28,
    title: 'Sample Title 28',
    language: 'Italian',
    'content type': 'Article',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant BB',
    'modified at': '2024-06-10',
    tags: ['tag55', 'tag56'],
    taxonomies: ['taxonomy55', 'taxonomy56'],
    actions: 'Edit/Delete',
  },
  {
    id: 29,
    title: 'Sample Title 29',
    language: 'Portuguese',
    'content type': 'Video',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant CC',
    'modified at': '2024-06-11',
    tags: ['tag57', 'tag58'],
    taxonomies: ['taxonomy57', 'taxonomy58'],
    actions: 'Edit/Delete',
  },
  {
    id: 30,
    title: 'Sample Title 30',
    language: ' Russian',
    'content type': 'Article',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant DD',
    'modified at': '2024-06-12',
    tags: ['tag59', 'tag60'],
    taxonomies: ['taxonomy59', 'taxonomy60'],
    actions: 'Edit/Delete',
  },
  {
    id: 31,
    title: 'Sample Title 31',
    language: 'Chinese',
    'content type': 'Video',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant EE',
    'modified at': '2024-06-13',
    tags: ['tag61', 'tag62'],
    taxonomies: ['taxonomy61', 'taxonomy62'],
    actions: 'Edit/Delete',
  },
  {
    id: 32,
    title: 'Sample Title 32',
    language: 'Spanish',
    'content type': 'Article',
    version: 3,
    'publish status': 'Published',
    'variant info': 'Variant FF',
    'modified at': '2024-06-14',
    tags: ['tag63', 'tag64'],
    taxonomies: ['taxonomy63', 'taxonomy64'],
    actions: 'Edit/Delete',
  },
  {
    id: 33,
    title: 'Sample Title 33',
    language: 'French',
    'content type': 'Video',
    version: 1,
    'publish status': 'Draft',
    'variant info': 'Variant GG',
    'modified at': '2024-06-15',
    tags: ['tag65', 'tag66'],
    taxonomies: ['taxonomy65', 'taxonomy66'],
    actions: 'Edit/Delete',
  },
  {
    id: 34,
    title: 'Sample Title 34',
    language: 'German',
    'content type': 'Article',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant HH',
    'modified at': '2024-06-16',
    tags: ['tag67', 'tag68'],
    taxonomies: ['taxonomy67', 'taxonomy68'],
    actions: 'Edit/Delete',
  },
  {
    id: 35,
    title: 'Sample Title 35',
    language: 'Italian',
    'content type': 'Video',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant II',
    'modified at': '2024-06-17',
    tags: ['tag69', 'tag70'],
    taxonomies: ['taxonomy69', 'taxonomy70'],
    actions: 'Edit/Delete',
  },
  {
    id: 36,
    title: 'Sample Title 36',
    language: 'Portuguese',
    'content type': 'Article',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant JJ',
    'modified at': '2024-06-18',
    tags: ['tag71', 'tag72'],
    taxonomies: ['taxonomy71', 'taxonomy72'],
    actions: 'Edit/Delete',
  },
  {
    id: 37,
    title: 'Sample Title 36',
    language: 'Portuguese',
    'content type': 'BLOG',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant JJ',
    'modified at': '2024-06-18',
    tags: ['tag71', 'tag72'],
    taxonomies: ['taxonomy71', 'taxonomy72'],
    actions: 'Edit/Delete',
  },
  {
    id: 38,
    title: 'Sample Title 38',
    language: 'German',
    'content type': 'BLOG',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant KK',
    'modified at': '2024-06-20',
    tags: ['tag73', 'tag74'],
    taxonomies: ['taxonomy73', 'taxonomy74'],
    actions: 'Edit/Delete',
  },
  {
    id: 39,
    title: 'Sample Title 39',
    language: 'Italian',
    'content type': 'News',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant LL',
    'modified at': '2024-06-22',
    tags: ['tag75', 'tag76'],
    taxonomies: ['taxonomy75', 'taxonomy76'],
    actions: 'Edit/Delete',
  },
  {
    id: 40,
    title: 'Sample Title 40',
    language: 'Korean',
    'content type': 'PODCAST',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant MM',
    'modified at': '2024-06-25',
    tags: ['tag77', 'tag78'],
    taxonomies: ['taxonomy77', 'taxonomy78'],
    actions: 'Edit/Delete',
  },
  {
    id: 41,
    title: 'Sample Title 41',
    language: 'English',
    'content type': 'ARTICLE',
    version: 2,
    'publish status': 'Draft',
    'variant info': 'Variant NN',
    'modified at': '2024-06-27',
    tags: ['tag79', 'tag80'],
    taxonomies: ['taxonomy79', 'taxonomy80'],
    actions: 'Edit/Delete',
  },
  {
    id: 42,
    title: 'Sample Title 42',
    language: 'French',
    'content type': 'VIDEO',
    version: 2,
    'publish status': 'Published',
    'variant info': 'Variant OO',
    'modified at': '2024-06-29',
    tags: ['tag81', 'tag82'],
    taxonomies: ['taxonomy81', 'taxonomy82'],
    actions: 'Edit/Delete',
  },
  {
    id: 43,
    title: 'Sample Title 43',
    language: 'Spanish',
    'content type': 'BLOG',
    version: 3,
    'publish status': 'Draft',
    'variant info': 'Variant PP',
    'modified at': '2024-06-27',
    tags: ['tag83', 'tag84'],
    taxonomies: ['taxonomy83', 'taxonomy84'],
    actions: 'Edit/Delete',
  },
  {
    id: 44,
    title: 'Sample Title 44',
    language: 'Japanese',
    'content type': 'ARTICLE',
    version: 1,
    'publish status': 'Published',
    'variant info': 'Variant QQ',
    'modified at': '2024-06-30',
    tags: ['tag85', 'tag86'],
    taxonomies: ['taxonomy85', 'taxonomy86'],
    actions: 'Edit/Delete',
  },
];
